<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_HtmlSiteMap
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<?php
/**
 * SEO Toolbar template
 *
 * @var $block Mavenbird\HtmlSiteMap\Block\ItemsCollection
 */
?>
<?php
$helper = $block->getHelper();
$baseUrl = $helper->getBaseUrl();
$getEnable = $helper->isEnable();
$urlKey = $helper->getModuleRoute();
$titleSiteMap = $helper->getTitleSiteMap();
$showLinkAt = $helper->getShowLinkAt();
?>
<?php if ($getEnable && $showLinkAt === 'top') : ?>
    <li>
        <a href="<?php echo $baseUrl . $urlKey; ?>"><?php echo $block->escapeHtml($titleSiteMap); ?></a>
    </li>
<?php
endif;
