<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_HtmlSiteMap
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<?php
/**
 * SEO Toolbar template
 *
 * @var $block Mavenbird\HtmlSiteMap\Block\ProductCollection
 */
?>
<?php
$helper = $block->getHelper();

//Product Link
$enableProduct = $helper->isEnableProduct();
$titleProduct = $helper->titleProduct();

if ($enableProduct) : ?>
    <h2 class="mavenbird_h2"><?php echo $titleProduct; ?></h2>
    <div class="mavenbird_site_map_grid">
        <?php
        $productCollection = $block->getProductCollection();
        foreach ($productCollection as $product) {
            echo $product->getData("id");
            echo '<div class="col-mavenbird-3">
                    <h3 class="mavenbird_product_list">
                    <a href="'.$product->getUrlModel()->getUrl($product).'"
                    title = "'.$product->getName().'">'.$product->getName().'</a>
                    </h3>
                </div>';
        }
        ?>
    </div>
    <?php
endif; ?>